#!/usr/bin/env bash
#
# scripts/aliyun-build.sh - macOS/Linux twin of tools/aliyun-build.ps1.
#
# On-demand Aliyun build. Launches a build ECS from the warm
# `qalos-build-warm` custom image, runs tools/do-build.sh on it
# (the SAME on-host script the DO path uses), pulls artifacts off, and
# destroys the ECS.
#
# Single source of truth: the on-host script is tools/do-build.sh. Only
# the orchestrator differs. This is the point of the design.
#
# Cost: depends on the build instance type. Default 'ecs.e-c1m1.large' is
# ~¥0.18/hr. A full AOSP build takes 2-6 hours.
#
# Usage:
#   ./scripts/aliyun-build.sh
#   ./scripts/aliyun-build.sh --instance-type ecs.u1-c1m8.2xlarge --max-runtime-minutes 360
#   ./scripts/aliyun-build.sh --build-variant eng

set -euo pipefail

REGION="cn-hangzhou"
BUILD_NAME="qalos-build"
INSTANCE_TYPE="ecs.e-c1m1.large"   # default small; swap in u1-c1m8.2xlarge for real build
BUILD_VARIANT="userdebug"
AOSP_TAG="android-15.0.0_r1"
MAX_RUNTIME_MINUTES=240
ARTIFACT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/out/aliyun-build"
PREFIX="qalos-smoke"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --region)             REGION="$2"; shift 2 ;;
        --instance-type)      INSTANCE_TYPE="$2"; shift 2 ;;
        --build-variant)      BUILD_VARIANT="$2"; shift 2 ;;
        --aosp-tag)           AOSP_TAG="$2"; shift 2 ;;
        --max-runtime-minutes) MAX_RUNTIME_MINUTES="$2"; shift 2 ;;
        --artifact-dir)       ARTIFACT_DIR="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,30p' "$0"
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/log.sh
source "$SCRIPT_DIR/lib/log.sh"
# shellcheck source=lib/aliyun-common.sh
source "$SCRIPT_DIR/lib/aliyun-common.sh"

require_aliyun
require_jq
require_ssh

# Load infra state
if [[ ! -f "$QALOS_STATE_FILE" ]]; then
    log_fatal "state file not found: $QALOS_STATE_FILE. Run scripts/aliyun-smoke-test.sh and scripts/aliyun-setup-base.sh first."
fi
if ! jq -e '.warmImageId' "$QALOS_STATE_FILE" >/dev/null 2>&1; then
    log_fatal "state file has no warmImageId. Run scripts/aliyun-setup-base.sh to create the warm custom image."
fi
eval "$(jq -r '@sh "REGION=\(.region) ZONE=\(.zone) VPC_ID=\(.vpcId) VSW_ID=\(.vswId) SG_ID=\(.sgId) KP_NAME=\(.keyPairName) IMAGE_ID=\(.warmImageId)"' "$QALOS_STATE_FILE")"
log_info "using warm image $IMAGE_ID (region $REGION, zone $ZONE)"

# Write the env file that the on-host script will source
ENV_FILE="$(mktemp)"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/aliyun-build.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
QALOS_REPO_URL='https://github.com/bramburn/qalos.git'
AOSP_TAG='$AOSP_TAG'
BUILD_TARGET='qalos_emulator'
BUILD_VARIANT='$BUILD_VARIANT'
MAX_RUNTIME_MINUTES='$MAX_RUNTIME_MINUTES'
EOF

# Launch the build ECS
now="$(date +%H%M%S)"
instance_name="${BUILD_NAME}-${now}"
log_info "launching $instance_name ($INSTANCE_TYPE)..."
INSTANCE_ID="$(aliyon ecs RunInstances \
    --RegionId "$REGION" \
    --ImageId "$IMAGE_ID" \
    --InstanceType "$INSTANCE_TYPE" \
    --SecurityGroupId "$SG_ID" \
    --VSwitchId "$VSW_ID" \
    --InstanceName "$instance_name" \
    --InstanceChargeType 'PostPaid' \
    --InternetMaxBandwidthOut 10 \
    --InternetChargeType 'PayByTraffic' \
    --SystemDisk.Category 'cloud_essd' \
    --SystemDisk.Size 500 \
    --KeyPairName "$KP_NAME" \
    --Amount 1 \
    | jq -r '.InstanceIdSets.InstanceIdSet[0]')"
log_info "instance: $INSTANCE_ID"

# Background watchdog
with_watchdog "$REGION" "$INSTANCE_ID"

cleanup() {
    local exit_code=$?
    log_info "destroying build ECS $INSTANCE_ID..."
    stop_watchdog
    aliyon ecs StopInstance --RegionId "$REGION" --InstanceId "$INSTANCE_ID" >/dev/null 2>&1 || true
    sleep 8
    aliyon ecs DeleteInstance --RegionId "$REGION" --InstanceId "$INSTANCE_ID" --Force true >/dev/null 2>&1 || true
    rm -f "$ENV_FILE"
    return $exit_code
}
trap cleanup EXIT INT TERM

# Wait for Running + get public IP
public_ip=""
deadline=$(( $(date +%s) + 300 ))
while [[ $(date +%s) -lt $deadline ]]; do
    inst="$(aliyon ecs DescribeInstances --RegionId "$REGION" --InstanceIds "['$INSTANCE_ID']" \
        | jq -r '.Instances.Instance[0] | "\(.Status)|\(.PublicIpAddress.IpAddress[0] // empty)"')"
    status="${inst%%|*}"
    public_ip="${inst#*|}"
    if [[ "$status" == "Running" && -n "$public_ip" ]]; then break; fi
    log_debug "  status=$status ip=$public_ip"
    sleep 5
done
if [[ -z "$public_ip" ]]; then
    log_fatal "build ECS did not become SSH-ready within 5 minutes"
fi
log_info "build ECS at $public_ip"

# Wait for SSH
ssh_ready=0
for _ in $(seq 1 30); do
    if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no "root@$public_ip" 'echo ready' >/dev/null 2>&1; then
        ssh_ready=1; break
    fi
    sleep 5
done
if [[ "$ssh_ready" -ne 1 ]]; then
    log_fatal "SSH not ready after 2.5 min. Aborting."
fi

# On-host watchdog (safety net #3)
log_info "starting on-host watchdog ($MAX_RUNTIME_MINUTES min cap)..."
cat > /tmp/onhost-watchdog.sh <<WD
#!/bin/bash
set -e
MAX_MIN=$MAX_RUNTIME_MINUTES
START_TS=\$(date +%s)
while true; do
  NOW_TS=\$(date +%s)
  ELAPSED_MIN=\$(( (NOW_TS - START_TS) / 60 ))
  if [ "\$ELAPSED_MIN" -ge "\$MAX_MIN" ]; then
    echo "[on-host watchdog] \$MAX_MIN min reached. Forcing shutdown." >&2
    shutdown -h now
    exit 0
  fi
  sleep 60
done
WD
scp /tmp/onhost-watchdog.sh "root@${public_ip}:/tmp/onhost-watchdog.sh"
ssh "root@$public_ip" 'chmod +x /tmp/onhost-watchdog.sh && nohup /tmp/onhost-watchdog.sh > /var/log/qalos-watchdog.log 2>&1 &'

# Run the on-host build
log_info "running tools/do-build.sh on the build ECS (this takes 1-6 hours)..."
do_build="$SCRIPT_DIR/../tools/do-build.sh"
if [[ ! -f "$do_build" ]]; then
    log_fatal "do-build.sh not found at $do_build"
fi
scp "$do_build" "root@${public_ip}:/tmp/do-build.sh"
scp "$ENV_FILE" "root@${public_ip}:/tmp/qalos-env.sh"
ssh "root@$public_ip" "source /tmp/qalos-env.sh && bash /tmp/do-build.sh"

# Pull the artifacts
log_info "pulling artifacts..."
mkdir -p "$ARTIFACT_DIR"
scp -r "root@${public_ip}:~/aosp/out/target/product/qalos_emulator/*.img" "$ARTIFACT_DIR/" || true
log_info "artifacts downloaded to $ARTIFACT_DIR"

echo ""
log_info "PASS"
echo "  artifacts  : $ARTIFACT_DIR"
exit 0
