# qalos - on-demand Aliyun build.
#
# Mirrors tools\doctl-build.ps1 for the DigitalOcean path. Launches a build ECS
# from the warm `qalos-build-warm` custom image, runs tools\do-build.sh on it
# (the SAME on-host script the DO path uses - it does the AOSP build and tries
# to upload artifacts to DO Spaces; the Aliyun variant currently falls back to
# scp'ing artifacts out from the orchestrator), then destroys the ECS.
#
# Single source of truth: the on-host script is tools\do-build.sh. Only the
# orchestrator differs. This is the point of the design - if the AOSP build
# steps change, they change in one place.
#
# Cost: depends on the build instance type. Default 'ecs.e-c1m1.large' is
# ~0.18 CNY/hr. A full AOSP build takes 2-6 hours. The warm image
# eliminates the 30-60 min apt-install step the DO path also avoids.
#
# Run from D:\qalos:
#     .\tools\aliyun-build.ps1
#     .\tools\aliyun-build.ps1 -InstanceType ecs.u1-c1m8.2xlarge   # 8 vCPU / 64 GB
#     .\tools\aliyun-build.ps1 -BuildVariant eng
#     .\tools\aliyun-build.ps1 -MaxRuntimeMinutes 360

[CmdletBinding()]
param(
    [string]$Region              = 'cn-hangzhou',
    [string]$BuildName           = 'qalos-build',
    [string]$InstanceType        = 'ecs.e-c1m1.large',  # default small; swap in u1-c1m8.2xlarge for real build
    [string]$BuildVariant        = 'userdebug',
    [string]$AospTag             = 'android-15.0.0_r1',
    [int]   $MaxRuntimeMinutes   = 240,
    [string]$ArtifactDownloadDir = (Join-Path $PSScriptRoot '..\out\aliyun-build'),
    [string]$Prefix              = 'qalos-smoke'
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

$aliyun = Join-Path $env:LOCALAPPDATA 'AliyunCLI\aliyun.exe'
if (-not (Test-Path $aliyun)) { throw "aliyun CLI not found. Run tools\aliyun-install.ps1 first." }
if (-not (& $aliyun configure list 2>&1 | Out-String | Select-String -Pattern 'default\s*\*')) {
    throw "no default aliyun profile. Run 'aliyun configure' first."
}

# Load infra state
$stateFile = Join-Path $PSScriptRoot '..\.pi\aliyun-state.json'
if (-not (Test-Path $stateFile)) { throw "state file not found: $stateFile. Run tools\aliyun-smoke-test.ps1 (one-time) and tools\aliyun-setup-base.ps1 (one-time, creates the warm image) first." }
$state = Get-Content $stateFile -Raw | ConvertFrom-Json
if (-not $state.warmImageId) { throw "state file has no warmImageId. Run tools\aliyun-setup-base.ps1 to create the warm custom image." }
$Region = $state.region
$Zone   = $state.zone
$vpcId  = $state.vpcId
$vswId  = $state.vswId
$sgId   = $state.sgId
$kpName = $state.keyPairName
$imageId = $state.warmImageId
Write-Host "[build] using warm image $imageId (region $Region, zone $Zone)"

# Write a build env file we'll scp to the instance.
$envFile = Join-Path $env:TEMP 'qalos-env.sh'
$envContent = @"
# Generated by tools\aliyun-build.ps1 at $(Get-Date -Format o)
QALOS_REPO_URL='https://github.com/bramburn/qalos.git'
AOSP_TAG='$AospTag'
BUILD_TARGET='qalos_emulator'
BUILD_VARIANT='$BuildVariant'
MAX_RUNTIME_MINUTES='$MaxRuntimeMinutes'
# Credentials for the DO Spaces upload inside do-build.sh (same as the DO path).
# NOTE: for the Aliyun path the orchestrator scp's artifacts out instead - the
# Spaces block below is unused unless you turn it on. Remove the creds to be safe.
# SPACES_BUCKET='unused'
# SPACES_REGION='unused'
# SPACES_KEY='unused'
# SPACES_SECRET='unused'
"@
Set-Content -Path $envFile -Value $envContent -Encoding UTF8

# Launch the build ECS
$now = (Get-Date).ToString('HHmmss')
$instanceName = "$BuildName-$now"
Write-Host "[build] launching $instanceName ($InstanceType)..." -ForegroundColor Cyan
$ri = & $aliyun ecs RunInstances `
    --RegionId $Region `
    --ImageId $imageId `
    --InstanceType $InstanceType `
    --SecurityGroupId $sgId `
    --VSwitchId $vswId `
    --InstanceName $instanceName `
    --InstanceChargeType PostPaid `
    --InternetMaxBandwidthOut 10 `
    --InternetChargeType PayByTraffic `
    --SystemDisk.Category cloud_essd `
    --SystemDisk.Size 500 `
    --KeyPairName $kpName `
    --Amount 1 `
    --HostName "qalos-build-$now" 2>&1 | Out-String
$idx = $ri.IndexOf('{')
if ($idx -lt 0) { throw "RunInstances returned no JSON. Output: $ri" }
$instanceId = ($ri.Substring($idx) | ConvertFrom-Json).InstanceIdSets.InstanceIdSet[0]
Write-Host "[build] instance: $instanceId" -ForegroundColor Green

# Watchdog - force-destroy the instance if this script is hard-killed
$watchdog = Start-Job -ScriptBlock {
    param($aliyunPath, $region, $instanceId, $parentPid)
    while ($true) {
        Start-Sleep -Seconds 5
        $parent = Get-Process -Id $parentPid -ErrorAction SilentlyContinue
        if (-not $parent) {
            & $aliyunPath ecs StopInstance  --RegionId $region --InstanceId $instanceId 2>$null | Out-Null
            Start-Sleep -Seconds 5
            & $aliyunPath ecs DeleteInstance --RegionId $region --InstanceId $instanceId --Force true 2>$null | Out-Null
            exit 0
        }
    }
} -ArgumentList @($aliyun, $Region, $instanceId, $PID)

$buildSucceeded = $false
$publicIp = $null
try {
    # Wait for Running
    $deadline = (Get-Date).AddMinutes(5)
    while ((Get-Date) -lt $deadline) {
        $d = & $aliyun ecs DescribeInstances --RegionId $Region --InstanceIds "['$instanceId']" 2>&1 | Out-String
        $didx = $d.IndexOf('{')
        $obj = if ($ddidx -ge 0) { $d.Substring($didx) | ConvertFrom-Json } else { $null }
        $inst = $obj.Instances.Instance
        if ($inst) {
            $status = $inst[0].Status
            $publicIp = $inst[0].PublicIpAddress.IpAddress
            if ($publicIp -is [array]) { $publicIp = $publicIp[0] }
            if ($status -eq 'Running' -and $publicIp) { break }
            Write-Host "  status=$status ip=$publicIp" -ForegroundColor DarkGray
        }
        Start-Sleep -Seconds 5
    }
    if (-not $publicIp) { throw "build ECS did not become SSH-ready within 5 minutes" }
    Write-Host "[build] build ECS at $publicIp" -ForegroundColor Green

    # Wait for SSH
    $sshReady = $false
    for ($i = 0; $i -lt 30; $i++) {
        if (ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no "root@$publicIp" "echo ready" 2>$null) {
            $sshReady = $true; break
        }
        Start-Sleep -Seconds 5
    }
    if (-not $sshReady) { throw "SSH not ready after 2.5 min. Aborting." }

    # On-host watchdog - shutdown the instance if the orchestrator loses contact.
    # This is safety net #3 (matches the DO path's on-droplet watchdog).
    $onHostWd = @"
#!/bin/bash
# On-host watchdog: if $MaxRuntimeMinutes pass, self-destruct.
# Started by the orchestrator in the background.
set -e
MAX_MIN=$MaxRuntimeMinutes
START_TS=`$(date +%s)
while true; do
  NOW_TS=`$(date +%s)
  ELAPSED_MIN=`$(( (NOW_TS - START_TS) / 60 ))
  if [ "`$ELAPSED_MIN" -ge "`$MAX_MIN" ]; then
    echo "[on-host watchdog] `$MAX_MIN min reached. Forcing shutdown." >&2
    shutdown -h now
    exit 0
  fi
  sleep 60
done
"@
    Write-Host "[build] starting on-host watchdog ($MaxRuntimeMinutes min cap)..." -ForegroundColor DarkGray
    $onHostPath = Join-Path $env:TEMP 'onhost-watchdog.sh'
    Set-Content -Path $onHostPath -Value $onHostWd -Encoding UTF8
    scp $onHostPath "root@${publicIp}:/tmp/onhost-watchdog.sh"
    ssh "root@$publicIp" "chmod +x /tmp/onhost-watchdog.sh && nohup /tmp/onhost-watchdog.sh > /var/log/qalos-watchdog.log 2>&1 &"

    # Run the on-host build
    Write-Host "[build] running tools\do-build.sh on the build ECS (this takes 1-6 hours)..." -ForegroundColor Cyan
    $doBuild = Join-Path $PSScriptRoot 'do-build.sh'
    if (-not (Test-Path $doBuild)) { throw "do-build.sh not found at $doBuild" }
    scp $doBuild "root@${publicIp}:/tmp/do-build.sh"
    scp $envFile "root@${publicIp}:/tmp/qalos-env.sh"
    ssh "root@$publicIp" "source /tmp/qalos-env.sh && bash /tmp/do-build.sh"
    if ($LASTEXITCODE -ne 0) { throw "do-build.sh failed with exit $LASTEXITCODE" }
    $buildSucceeded = $true
    Write-Host "[build] on-host build complete" -ForegroundColor Green

    # Pull the artifacts
    Write-Host "[build] pulling artifacts..." -ForegroundColor Cyan
    if (-not (Test-Path $ArtifactDownloadDir)) { New-Item -ItemType Directory -Path $ArtifactDownloadDir -Force | Out-Null }
    # do-build.sh places artifacts in ~/aosp/out/target/product/qalos_emulator/
    scp -r "root@${publicIp}:~/aosp/out/target/product/qalos_emulator/*.img" $ArtifactDownloadDir
    Write-Host "[build] artifacts downloaded to $ArtifactDownloadDir" -ForegroundColor Green
}
finally {
    # Always destroy the build ECS
    Write-Host "[build] destroying build ECS $instanceId..." -ForegroundColor Cyan
    & $aliyun ecs StopInstance --RegionId $Region --InstanceId $instanceId 2>&1 | Out-Null
    Start-Sleep -Seconds 8
    & $aliyun ecs DeleteInstance --RegionId $Region --InstanceId $instanceId --Force true 2>&1 | Out-Null
    if ($watchdog) { Stop-Job -Job $watchdog -ErrorAction SilentlyContinue; Remove-Job -Job $watchdog -Force -ErrorAction SilentlyContinue }
}

if ($buildSucceeded) {
    Write-Host ""
    Write-Host "[build] PASS" -ForegroundColor Green
    Write-Host "  artifacts  : $ArtifactDownloadDir"
    exit 0
} else {
    Write-Host ""
    Write-Host "[build] FAIL (build ECS was destroyed in finally{})" -ForegroundColor Red
    exit 1
}
